DROP TABLE IF EXISTS `FRAMEWORK_SYS_USER`;
CREATE TABLE `FRAMEWORK_SYS_USER` (
  `ID` varchar(32) NOT NULL COMMENT 'ID',
  `SU_LOGIN_NAME` varchar(20) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '登录名',
  `SU_LOGIN_PASS` varchar(32) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL COMMENT '登录密码',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户表';